name: Fetch Daily Wallpaper

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:      # 允许手动触发

jobs:
  fetch:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build fetch tool
      run: go build -o fetch ./cmd/fetch

    - name: Fetch wallpapers
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: ./fetch

    - name: Clean up
      run: rm fetch 